#if UNITY_EDITOR
using TheFusionEngineer.Core;
using TheFusionEngineer.Stage01;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

public static class Stage01DensePackingBuilder
{
    private static Transform layout;
    private static Material wall, dark, steel, blue, green, yellow, black, carrier, pallet, white;

    [MenuItem("The Fusion Engineer/Build Stage01 Dense Packing Layout")]
    public static void Apply()
    {
        var scene = UnityEngine.SceneManagement.SceneManager.GetActiveScene();
        if (scene.name != "Stage01_Origin") throw new System.Exception("Stage01_Origin must be active.");
        GameObject env = GameObject.Find("Stage01_Environment");
        if (env == null) throw new System.Exception("Stage01_Environment missing.");
        GameObject old = GameObject.Find("Stage01_ProductionLayout");
        if (old != null) Object.DestroyImmediate(old);
        var root = new GameObject("Stage01_ProductionLayout"); root.transform.SetParent(env.transform, false); layout = root.transform;
        wall=Mat("Wall",new Color(.62f,.69f,.72f)); dark=Mat("Dark",new Color(.055f,.085f,.11f),.55f,.6f);
        steel=Mat("Steel",new Color(.42f,.48f,.52f),.65f,.72f); blue=Mat("Blue",new Color(.02f,.30f,.52f),.25f,.65f);
        green=Mat("Green",new Color(.05f,.48f,.25f)); yellow=Mat("Yellow",new Color(.95f,.62f,.03f));
        black=Mat("Black",new Color(.025f,.03f,.035f)); carrier=Mat("Carrier",new Color(.32f,.55f,.66f),.25f,.75f);
        pallet=Mat("Pallet",new Color(.34f,.20f,.09f)); white=Mat("LED",new Color(.9f,.96f,1f));
        BuildPLC(); BuildConveyor(); BuildRobot(); BuildPacking(); BuildUtility(); BuildExit(); BuildWalkway(); BuildCeiling(); BuildBranding(); SetupFPS();
        if (env.transform.Find("Stage01_DisabledArt") == null) { var d=new GameObject("Stage01_DisabledArt"); d.transform.SetParent(env.transform,false); d.SetActive(false); }
        EditorSceneManager.MarkSceneDirty(scene); EditorSceneManager.SaveScene(scene); AssetDatabase.SaveAssets();
    }

    private static Material Mat(string n,Color c,float metal=0,float smooth=.35f){ var m=new Material(Shader.Find("Universal Render Pipeline/Lit")){name="S01_"+n,color=c};m.SetFloat("_Metallic",metal);m.SetFloat("_Smoothness",smooth);return m; }
    private static Transform Root(string n){var g=new GameObject(n);g.transform.SetParent(layout,false);return g.transform;}
    private static GameObject Box(Transform p,string n,Vector3 pos,Vector3 scale,Material m){var g=GameObject.CreatePrimitive(PrimitiveType.Cube);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;g.GetComponent<Renderer>().sharedMaterial=m;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
    private static GameObject Cyl(Transform p,string n,Vector3 pos,Vector3 scale,Material m,Vector3 rot){var g=GameObject.CreatePrimitive(PrimitiveType.Cylinder);g.name=n;g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localScale=scale;g.transform.localEulerAngles=rot;g.GetComponent<Renderer>().sharedMaterial=m;Object.DestroyImmediate(g.GetComponent<Collider>());return g;}
    private static void Sign(Transform p,string text,Vector3 pos,Vector3 rot,float size){var g=new GameObject("Sign_"+text.Replace(" ","_"));g.transform.SetParent(p,false);g.transform.localPosition=pos;g.transform.localEulerAngles=rot;var t=g.AddComponent<TextMesh>();t.text=text;t.fontSize=64;t.characterSize=size;t.anchor=TextAnchor.MiddleCenter;t.alignment=TextAlignment.Center;t.color=Color.white;}
    private static void Border(Transform p,Vector3 c,Vector2 s){Box(p,"Hazard_Y1",c+new Vector3(0,.015f,s.y/2),new Vector3(s.x,.03f,.08f),yellow);Box(p,"Hazard_Y2",c-new Vector3(0,-.015f,s.y/2),new Vector3(s.x,.03f,.08f),yellow);Box(p,"Hazard_B1",c+new Vector3(s.x/2,.018f,0),new Vector3(.08f,.035f,s.y),black);Box(p,"Hazard_B2",c-new Vector3(s.x/2,-.018f,0),new Vector3(.08f,.035f,s.y),black);}
    private static void Fence(Transform p,Vector3 a,Vector3 b){Vector3 mid=(a+b)*.5f,dir=b-a;var r=Box(p,"FenceRail",mid+Vector3.up*.75f,new Vector3(.07f,.07f,Vector3.Distance(a,b)),yellow);r.transform.rotation=Quaternion.LookRotation(dir);Box(p,"FencePost",a+Vector3.up*.55f,new Vector3(.1f,1.1f,.1f),yellow);Box(p,"FencePost",b+Vector3.up*.55f,new Vector3(.1f,1.1f,.1f),yellow);}

    private static void BuildPLC(){Transform r=Root("PLCInspectionZone");Box(r,"ControlCabinet",new Vector3(2.5f,1.5f,-2.45f),new Vector3(2.2f,3,.55f),dark);Box(r,"WorkConsole",new Vector3(4.2f,.85f,-1.6f),new Vector3(1.4f,1.7f,.7f),steel);Box(r,"InspectionMonitor",new Vector3(4.2f,1.55f,-1.18f),new Vector3(1.05f,.7f,.08f),blue);Box(r,"SmallWorktable",new Vector3(.7f,.55f,-2.2f),new Vector3(1.3f,.12f,.8f),steel);Cyl(r,"StatusBeacon",new Vector3(3.35f,3.35f,-2.45f),new Vector3(.13f,.32f,.13f),green,Vector3.zero);Sign(r,"PLC CONTROL",new Vector3(2.5f,3.25f,-2.12f),Vector3.zero,.25f);Sign(r,"CL17 LINE MONITORING",new Vector3(4.2f,2.25f,-1.15f),Vector3.zero,.14f);Border(r,new Vector3(2.5f,.02f,-1.15f),new Vector2(3.6f,2.4f));}
    private static void BuildConveyor(){Transform r=Root("ConveyorProductionZone");for(int i=0;i<3;i++){float z=.8f+i*2.65f;Box(r,"ConveyorVisual_"+(i+1),new Vector3(5,.72f,z),new Vector3(2.3f,.22f,2.5f),dark);Box(r,"Belt_"+(i+1),new Vector3(5,.87f,z),new Vector3(1.85f,.08f,2.35f),steel);}Fence(r,new Vector3(3.65f,0,-.5f),new Vector3(3.65f,0,7.4f));Fence(r,new Vector3(6.35f,0,-.5f),new Vector3(6.35f,0,7.4f));Sign(r,"CONVEYOR PRODUCTION",new Vector3(5,2.7f,0),Vector3.zero,.2f);}
    private static void BuildRobot(){Transform r=Root("RobotTransferZone");Cyl(r,"RobotBase",new Vector3(7.8f,.28f,7.2f),new Vector3(.75f,.28f,.75f),dark,Vector3.zero);Cyl(r,"Axis1",new Vector3(7.8f,1.15f,7.2f),new Vector3(.42f,.9f,.42f),yellow,Vector3.zero);var a=Box(r,"RobotArm1",new Vector3(7.25f,2.05f,7.2f),new Vector3(.42f,1.6f,.42f),yellow);a.transform.localEulerAngles=new Vector3(0,0,42);a=Box(r,"RobotArm2",new Vector3(6.55f,2.72f,6.75f),new Vector3(.35f,1.35f,.35f),yellow);a.transform.localEulerAngles=new Vector3(35,0,55);Cyl(r,"Wrist",new Vector3(6.05f,2.95f,6.25f),new Vector3(.28f,.28f,.28f),dark,new Vector3(90,0,0));Box(r,"Gripper",new Vector3(5.65f,2.75f,5.9f),new Vector3(.65f,.12f,.15f),dark);Fence(r,new Vector3(7,0,5.5f),new Vector3(9.2f,0,5.5f));Fence(r,new Vector3(9.2f,0,5.5f),new Vector3(9.2f,0,8.8f));Border(r,new Vector3(8,.02f,7.2f),new Vector2(2.8f,3.4f));Sign(r,"ROBOT TRANSFER",new Vector3(8,3.5f,8.7f),new Vector3(0,180,0),.2f);}
    private static void BuildPacking(){Transform r=Root("PalletPackingZone");for(int p=0;p<4;p++){float x=-1.8f+(p%2)*2.2f,z=6.5f+(p/2)*2;Box(r,"Pallet_"+(p+1),new Vector3(x,.12f,z),new Vector3(1.65f,.24f,1.35f),pallet);}for(int c=0;c<9;c++){int col=c%3;Vector3 pos=c<6?new Vector3(-1.8f+(col-1)*.45f,.52f+(c/3)*.55f,6.5f):new Vector3(.4f+(col-1)*.5f,.5f,8.5f);Box(r,"GlassCarrier_"+(c+1),pos,new Vector3(.4f,.48f,.9f),carrier);}Box(r,"PackingTable",new Vector3(1.1f,.7f,6.4f),new Vector3(1.8f,1.4f,.9f),steel);Box(r,"WrapStation",new Vector3(-3.4f,1.1f,8.3f),new Vector3(.65f,2.2f,1.1f),blue);Border(r,new Vector3(-.8f,.02f,7.4f),new Vector2(6.8f,4.4f));Sign(r,"DENSE PACKING AREA",new Vector3(-.8f,3.2f,9.2f),new Vector3(0,180,0),.24f);}
    private static void BuildUtility(){Transform r=Root("UpperUtilityZone");for(int x=-8;x<=8;x+=4)Box(r,"PlatformColumn",new Vector3(x,2.2f,8.7f),new Vector3(.18f,4.4f,.18f),steel);Box(r,"UpperPlatform",new Vector3(0,4.15f,8.7f),new Vector3(18,.22f,1.8f),dark);Box(r,"UpperRail",new Vector3(0,4.95f,7.85f),new Vector3(18,.08f,.08f),yellow);for(int x=-8;x<=8;x+=2)Box(r,"RailPost",new Vector3(x,4.58f,7.85f),new Vector3(.08f,.85f,.08f),yellow);for(int x=-6;x<=6;x+=3)Cyl(r,"UtilityPipe",new Vector3(x,5.35f,8.8f),new Vector3(.11f,4.5f,.11f),blue,new Vector3(90,0,0));Box(r,"CableTray",new Vector3(0,5.55f,8.3f),new Vector3(16,.12f,.35f),steel);for(int s=0;s<6;s++)Box(r,"AccessStep",new Vector3(7.5f,.35f+s*.62f,7.3f+s*.18f),new Vector3(1.1f,.12f,.45f),steel);}
    private static void BuildExit(){Transform r=Root("CleanRoomExit");Box(r,"AirShower_Left",new Vector3(-6.65f,1.65f,6),new Vector3(.28f,3.3f,1.8f),steel);Box(r,"AirShower_Right",new Vector3(-3.35f,1.65f,6),new Vector3(.28f,3.3f,1.8f),steel);Box(r,"AirShower_Top",new Vector3(-5,3.2f,6),new Vector3(3.6f,.28f,1.8f),steel);Sign(r,"CLEAN ROOM EXIT",new Vector3(-5,3.55f,5.15f),Vector3.zero,.25f);}
    private static void BuildWalkway(){Transform r=Root("SafetyWalkway");Box(r,"MainGreenWalkway",new Vector3(-2.1f,.012f,1.8f),new Vector3(2.8f,.024f,13.8f),green);Box(r,"CrossWalkway",new Vector3(.6f,.014f,5.3f),new Vector3(7.8f,.026f,2.6f),green);for(int z=-5;z<=8;z+=2)Box(r,"WalkwayMarker",new Vector3(-3.48f,.025f,z),new Vector3(.08f,.035f,1.2f),yellow);}
    private static void BuildCeiling(){Transform r=Root("CeilingLineLighting");for(int z=-6;z<=6;z+=3){Box(r,"LED_Left",new Vector3(-3,5.85f,z),new Vector3(.25f,.1f,2.3f),white);Box(r,"LED_Right",new Vector3(4.8f,5.85f,z),new Vector3(.25f,.1f,2.3f),white);}}
    private static void BuildBranding(){Transform r=Root("CompanyBranding");Texture2D tex=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Resources/Branding/Corning_CI.png");if(tex==null){Debug.LogError("Corning CI texture reference is missing.");return;}var m=new Material(Shader.Find("Universal Render Pipeline/Unlit")){name="Corning_CI_Transparent"};m.SetTexture("_BaseMap",tex);m.SetColor("_BaseColor",Color.white);m.SetFloat("_Surface",1);m.SetFloat("_Cull",0);m.SetFloat("_ZWrite",0);m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");m.renderQueue=3000;var g=GameObject.CreatePrimitive(PrimitiveType.Quad);g.name="Corning_CI_WallPrint";g.transform.SetParent(r,false);g.transform.position=new Vector3(-9.81f,3.1f,0);g.transform.rotation=Quaternion.Euler(0,-90,0);g.transform.localScale=new Vector3(3.8f,1.25f,1);g.GetComponent<Renderer>().sharedMaterial=m;Object.DestroyImmediate(g.GetComponent<Collider>());Sign(r,"GLASS DENSE PACKING PROCESS",new Vector3(-9.79f,2.28f,0),new Vector3(0,-90,0),.12f);}
    private static void SetupFPS(){GameObject player=GameObject.Find("Player");Camera cam=Camera.main;if(player==null||cam==null)throw new System.Exception("Player or Main Camera missing.");var f=cam.GetComponent<CameraFollow>();if(f!=null)Object.DestroyImmediate(f);cam.transform.SetParent(player.transform,false);cam.transform.localPosition=new Vector3(0,.62f,0);cam.transform.localRotation=Quaternion.identity;cam.fieldOfView=68;var fps=cam.GetComponent<Stage01FirstPersonCamera>();if(fps==null)fps=cam.gameObject.AddComponent<Stage01FirstPersonCamera>();var so=new SerializedObject(fps);so.FindProperty("player").objectReferenceValue=player.transform;so.ApplyModifiedPropertiesWithoutUndo();}
}
#endif
